'use client'

import { useState, useEffect } from 'react'
import Link from 'next/link'
import { getExercises } from '@/lib/mock-data'
import { ExerciseGenerator } from '@/components/exercise-generator'
import { useAuth } from '@/contexts/auth-context'
import { createClient } from '@/lib/supabase/client'
import { BookOpen, ChevronRight, Filter } from 'lucide-react'

interface Exercise {
  id: string
  title: string
  description: string
  level: 'beginner' | 'intermediate' | 'advanced'
  category: string
  type: 'multiple-choice' | 'fill-blank' | 'matching' | 'listening'
}

export default function PracticePage() {
  const { user } = useAuth()
  const [exercises, setExercises] = useState<Exercise[]>([])
  const [isLoading, setIsLoading] = useState(true)
  const [selectedLevel, setSelectedLevel] = useState<'all' | 'beginner' | 'intermediate' | 'advanced'>('all')
  const [selectedCategory, setSelectedCategory] = useState<string>('all')

  // Fetch exercises from database and mock data
  useEffect(() => {
    const supabase = createClient()
    const fetchExercises = async () => {
      try {
        let data: Exercise[] = []

        // Try to fetch from Supabase if user is logged in
        if (user?.id) {
          const { data: dbExercises, error } = await supabase
            .from('exercises')
            .select('*')
            .eq('user_id', user.id)
            .order('created_at', { ascending: false })

          if (!error && dbExercises) {
            data = dbExercises.map((ex: any) => ({
              id: ex.id,
              title: ex.content?.title || 'Generated Exercise',
              description: ex.content?.description || 'Exercise generated by AI',
              level: ex.level || 'beginner',
              category: ex.topic || 'General',
              type: ex.type,
            }))
          }
        }

        // Combine with mock data
        const mockData = getExercises()
        setExercises([...data, ...mockData])
      } catch (error) {
        console.error('Error fetching exercises:', error)
        // Fallback to mock data only
        setExercises(getExercises())
      } finally {
        setIsLoading(false)
      }
    }

    fetchExercises()
  }, [user?.id])

  const levels = ['all', 'beginner', 'intermediate', 'advanced'] as const
  const categories = ['all', ...new Set(exercises.map((e) => e.category))]

  const filteredExercises = exercises.filter((exercise) => {
    const levelMatch = selectedLevel === 'all' || exercise.level === selectedLevel
    const categoryMatch = selectedCategory === 'all' || exercise.category === selectedCategory
    return levelMatch && categoryMatch
  })

  const getLevelColor = (level: string) => {
    switch (level) {
      case 'beginner':
        return 'bg-green-100/20 text-green-700 dark:text-green-400'
      case 'intermediate':
        return 'bg-yellow-100/20 text-yellow-700 dark:text-yellow-400'
      case 'advanced':
        return 'bg-red-100/20 text-red-700 dark:text-red-400'
      default:
        return ''
    }
  }

  const handleExerciseGenerated = (exercise: any) => {
    // Add newly generated exercise to the list
    const newExercise: Exercise = {
      id: exercise.id,
      title: exercise.content?.title || 'Generated Exercise',
      description: exercise.content?.description || 'Exercise generated by AI',
      level: exercise.level || 'beginner',
      category: exercise.topic || 'General',
      type: exercise.type,
    }
    setExercises([newExercise, ...exercises])
  }

  return (
    <div className="space-y-8">
      {/* Header */}
      <div>
        <h1 className="text-4xl font-bold mb-2">Practice Exercises</h1>
        <p className="text-muted-foreground">
          Choose from carefully designed exercises or generate new ones with AI
        </p>
      </div>

      {/* Exercise Generator */}
      <ExerciseGenerator onExerciseGenerated={handleExerciseGenerated} />

      {/* Filters */}
      <div className="space-y-4">
        <div className="flex items-center gap-2 mb-4">
          <Filter className="h-5 w-5 text-muted-foreground" />
          <span className="font-semibold">Filters</span>
        </div>

        <div className="grid gap-4 md:grid-cols-2">
          <div>
            <label className="mb-2 block text-sm font-medium">Level</label>
            <div className="flex flex-wrap gap-2">
              {levels.map((level) => (
                <button
                  key={level}
                  onClick={() => setSelectedLevel(level)}
                  className={`rounded-full px-4 py-2 text-sm font-medium transition-colors ${
                    selectedLevel === level
                      ? 'bg-primary text-primary-foreground'
                      : 'bg-muted text-foreground hover:bg-muted/80'
                  }`}
                >
                  {level.charAt(0).toUpperCase() + level.slice(1)}
                </button>
              ))}
            </div>
          </div>

          <div>
            <label className="mb-2 block text-sm font-medium">Category</label>
            <select
              value={selectedCategory}
              onChange={(e) => setSelectedCategory(e.target.value)}
              className="w-full rounded-lg border border-input bg-background px-3 py-2 focus:outline-none focus:ring-2 focus:ring-ring"
            >
              {categories.map((category) => (
                <option key={category} value={category}>
                  {category.charAt(0).toUpperCase() + category.slice(1)}
                </option>
              ))}
            </select>
          </div>
        </div>
      </div>

      {/* Exercises Grid */}
      <div>
        <p className="text-sm text-muted-foreground mb-4">
          Showing {filteredExercises.length} exercise{filteredExercises.length !== 1 ? 's' : ''}
        </p>

        {filteredExercises.length > 0 ? (
          <div className="grid gap-4 md:grid-cols-2">
            {filteredExercises.map((exercise) => (
              <Link
                key={exercise.id}
                href={`/dashboard/practice/${exercise.id}`}
                className="group rounded-lg border border-border bg-card p-6 hover:border-primary hover:shadow-md transition-all cursor-pointer"
              >
                <div className="flex items-start justify-between mb-3">
                  <BookOpen className="h-6 w-6 text-primary" />
                  <span className={`px-2 py-1 rounded-full text-xs font-medium ${getLevelColor(exercise.level)}`}>
                    {exercise.level}
                  </span>
                </div>

                <h3 className="font-semibold mb-2 group-hover:text-primary transition-colors line-clamp-2">
                  {exercise.title}
                </h3>

                <p className="text-sm text-muted-foreground mb-4 line-clamp-2">
                  {exercise.description}
                </p>

                <div className="flex items-center justify-between text-sm">
                  <span className="text-xs bg-muted px-2 py-1 rounded">{exercise.category}</span>
                  <ChevronRight className="h-4 w-4 text-muted-foreground group-hover:text-primary transition-colors" />
                </div>
              </Link>
            ))}
          </div>
        ) : (
          <div className="rounded-lg border border-border bg-card p-12 text-center">
            <p className="text-muted-foreground mb-4">No exercises found with the selected filters.</p>
            <button
              onClick={() => {
                setSelectedLevel('all')
                setSelectedCategory('all')
              }}
              className="text-primary hover:underline font-medium"
            >
              Clear filters
            </button>
          </div>
        )}
      </div>
    </div>
  )
}

