BEGIN;

CREATE TABLE IF NOT EXISTS public.ip_tracking_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  event_type TEXT NOT NULL CHECK (
    event_type IN (
      'login_success',
      'login_failed',
      'register_success',
      'register_failed',
      'logout'
    )
  ),
  ip_address INET NOT NULL,
  user_agent TEXT,
  path TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ip_tracking_events_user_created
  ON public.ip_tracking_events(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_ip_tracking_events_ip_created
  ON public.ip_tracking_events(ip_address, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_ip_tracking_events_type_created
  ON public.ip_tracking_events(event_type, created_at DESC);

ALTER TABLE public.ip_tracking_events ENABLE ROW LEVEL SECURITY;

CREATE POLICY ip_tracking_events_select_own ON public.ip_tracking_events
  FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY ip_tracking_events_insert_self_or_anon ON public.ip_tracking_events
  FOR INSERT
  WITH CHECK (
    (auth.uid() IS NULL AND user_id IS NULL)
    OR (auth.uid() IS NOT NULL AND (user_id IS NULL OR user_id = auth.uid()))
  );

COMMIT;
